### ISSUE TITLE
Any particular reason Ubuntu is not a supported OS?

### ISSUE THREAD

**Issue by brewboy** [Mindera/pm2-cookbook#10]
I don't see Ubuntu on the list of supported OSes, but looking through the code I don't see any reason it shouldn't work for it.  Was it just not an officially supported OS and/or it hasn't been tested on it?

I realize this might not be an "issue", but I don't see another place to ask this.

Thanks in advance,
Jon

**Comment by joaogbcravo** [comment]
As far as i know, It wasn't tested in ubuntu.

Did you want to test it and let us know if it need some kind of patch to work in ubuntu (or you can do the patch by yourself and make pull request :D )? 

Cheers,
João

**Comment by miguelcnf** [comment]
Yep it was a matter of "we didn't need it so we didn't test it".

It should generally work in ubuntu/debian but if we want to support it we need to add a kitchen suite for it.

**Comment by brewboy** [comment]
Thanks for the quick response.  If I end up using it I'll report back.

**Comment by miguelcnf** [comment]
I've pushed https://github.com/Mindera/pm2-cookbook/commit/51aeba41cb345947b2f5881763f3b6ee4dccd8e5 which adds support and kitchen platforms for ubuntu and debian.

Tested locally and it looks good on both - will be available on `0.5.0`.

**Comment by miguelcnf** [comment]
Supported in `0.5.0` just published.
