### ISSUE TITLE
Support for modifying the runas user

### ISSUE THREAD

**Issue by jarosser06** [Mindera/pm2-cookbook#3]
Its generally not a good practice to run applications as a privileged user so there should be a user option that allows pm2 to be run as that user.

**Comment by miguelcnf** [comment]
I agree - afaik pm2 has 2 ways of doing this:
- starting as the current shell user (start actions)
- starting as the user specified in the init script (startup action)

Neither is based on the configuration file [schema](https://github.com/Unitech/PM2/blob/master/lib%2Fschema.json) tho.

We'll want to cover both scenarios.

**Comment by jarosser06** [comment]
I have a PR incoming for this.

**Comment by jarosser06** [comment]
Added in #5

**Comment by miguelcnf** [comment]
Merged and released in [0.3.0](https://github.com/Mindera/pm2-cookbook/tree/0.3.0).

Thanks! :)
