### ISSUE TITLE
Berksfile.lock

### ISSUE THREAD

**Issue by jarosser06** [Mindera/pm2-cookbook#4]
Is there a particular reason your including the Berksfile.lock in this cookbook?  Usually the lock file is not checked in to library cookbooks.

**Comment by miguelcnf** [comment]
We tend to version the lock files to represent the last good known state in which the cookbook was validated. It also allows sharing a sane development/test environment to work on by locking transactive dependencies with which we had issues in the past with community libraries.

Have you had any issue with it or know of a reason why not to?

**Comment by jarosser06** [comment]
The lock file isn't getting updated when the cookbook version gets updated.  We generally try to keep the Berks lock files in our wrapper cookbooks because we have had issues with Library cookbooks manipulating berks in the past.

**Comment by miguelcnf** [comment]
I figure we can live without it and this way avoid getting other people in trouble.

Removed in https://github.com/Mindera/pm2-cookbook/commit/6a59121f5abbbb3555e14510d3cdc7a021261443.
