### ISSUE TITLE
Support for custom PM2_HOME locations

### ISSUE THREAD

**Issue by miguelcnf** [Mindera/pm2-cookbook#9]
As of [0.4.0](https://github.com/Mindera/pm2-cookbook/tree/0.4.0) we're overwriting the home attribute as `"#{::Dir.home(new_resource.user)}/.pm2"` since it's the only way PM2 is able to persist processes over reboots.

https://github.com/Unitech/PM2/pull/1213 should fix this and allow to have a custom PM2_HOME to be set. 

Even tho IMO we should force having the `.pm2` directory always appended.

Creating this to track it.

**Comment by jarosser06** [comment]
Was just debugging this issue on a staging node.

**Comment by miguelcnf** [comment]
This is being addressed in #11.

**Comment by miguelcnf** [comment]
Fixed in `0.6.0` released just now.
